/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackexchange;
import stackexchange.Controller;
import java.util.*; // Import the Scanner class to read text files
import java.io.InputStreamReader;

public class App {
    public void getGreeting(String s) {
        
        Controller controller=new Controller();
        controller.process(s);
        return ;
    }

    public static void main(String[] args) {
       
        if(args.length>0){
            Controller controller=new Controller();
            controller.process(args[0]);
        }
    }
}
