/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackexchange;
import stackexchange.Controller;
import java.util.*; // Import the Scanner class to read text files
import java.io.InputStreamReader;
import stackexchange.InputRuntimeException;

public class App {
   

    public static void main(String[] args) {
       
        if(args.length==1){
            Controller controller=new Controller();
            controller.process(args[0]);
        }
        else{
            throw new InputRuntimeException();
        }

    }
}
